apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: APP_NAME-stage
spec:
  project: default
  destination:
    namespace: stage-environment
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/GITHUB_STAGE_REPO.git
    path: DEPLOYMENT_PATH
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
